### PR TITLE
fixed wrong number of parameters for function connect()

### PR DESCRIPTION
**Pull request by rwx------**
fixed wrong number of parameters for function connect()

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@rwx------, documentation is correct. The fourth parameter is `persistent_id`.

**Comment by rwx------** [comment]
when I jump to the function in my IDE, I got this explaination ?
There is only 4 parameters.

```
/**
     * Connects to a Redis instance.
     *
     * @param  string    $host           can be a host, or the path to a unix domain socket
     * @param  int       $port           optional
     * @param  float     $timeout        value in seconds (optional, default is 0.0 meaning unlimited)
     * @param  int       $retry_interval retry interval in milliseconds.
     * @return bool                      TRUE on success, FALSE on error.
     * @example
     * <pre>
     * $redis->connect('127.0.0.1', 6379);
     * $redis->connect('127.0.0.1');            // port 6379 by default
     * $redis->connect('127.0.0.1', 6379, 2.5); // 2.5 sec timeout.
     * $redis->connect('/tmp/redis.sock');      // unix domain socket.
     * </pre>
     */
    public function connect( $host, $port = 6379, $timeout = 0.0, $retry_interval = 0 ) {}
```

**Comment by rwx------** [comment]
php version:  
```
$ php -version
PHP 7.0.14 (cli) (built: Dec  9 2016 07:34:25) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
phpredis version:  ( `php -i`  result)
```
redis
Redis Support => enabled
Redis Version => 3.0.0
```

**Comment by rwx------** [comment]
when I update my php and phpredis， It is still the same.
```
$ php -version
PHP 7.0.18 (cli) (built: Apr 16 2017 12:16:19) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```
phpredis version: ( php -i result)
```
redis
Redis Support => enabled
Redis Version => 3.1.1
```

**Comment by rwx------** [comment]
@yatsukhnenko , The `persistent_id` is the parameter of `pconnect()`.

**Comment by yatsukhnenko** [comment]
@rwx------, `connect` and `pconnect` are both use `redis_connect` wich parse parameters as `"Os|ldsld"`
@michael-grunder, as for me `persistent_id` doesn't have a sence in `connect` method but changing this may broke existing code.

**Comment by michael-grunder** [comment]
@yatsukhnenko The connection arguments (and their order) predates my involvement in the project by a long time.  With so many people using phpredis I'm not sure we can really do anything about it at this point.

We could modify the constructor to take arguments which would simplify the most common use case where you create a redis object and connect to a given host/port.  That wouldn't break existing installations as the constructor doesn't take any arguments now.

The other option would be to add static helper method(s) like `Redis::getConnection(host, port, ...)` but I'm not sure if it's really worth it at this point.

**Comment by yatsukhnenko** [comment]
@michael-grunder, what do you think about
```
$redis->connect('127.0.0.1', 6379, $options = array(
    'timeout' => 2.5,
    'retry_interval' => 1,
));
```
or even
```
$redis->connect(array(
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 2.5,
    'retry_interval' => 1,
));
```
We can easily detect `array` parameter and process it and users may use old and new connection style

**Pull request closed without merging**
