### PR TITLE
VC14 fixes (2) and a test fix

### PR DESCRIPTION
**Pull request by Jan-E**
Two fixes for VC14. The test fix is generic and should be applied to the other branches as well.

### CODE REVIEW

**Comment by michael-grunder** [comment]
@Jan-E Do you have an email address I can get you at?  If you don't want to post it here, feel free to email me, which is on my account and in the source files :)

**Comment by Jerry-Shaw** [comment]
New update comments?

**Comment by Jan-E** [comment]
phpdev@ehrhardt.nl

**Comment by Jan-E** [comment]
@Jerry-Shaw nothing essential, mostly cleanup. The php7 branch is as good as the branch for php5 before and after these commits.

**Comment by Jerry-Shaw** [comment]
Haha, if there are new ones, I'm glad to test again.

**Comment by Jan-E** [comment]
Not really needed. I already compiled PHP7 RC3 with this branch:
https://www.apachelounge.com/viewtopic.php?t=6617

**Comment by Jerry-Shaw** [comment]
Wow, that is good. I can use yours. Thanks so much, haha..

Just ready to get PHP7 RC3 now.

**Comment by Jan-E** [comment]
@michael-grunder Ping. Friendly reminder.

**Comment by michael-grunder** [comment]
Merged, thanks.

**Pull request merged**
