### PR TITLE
Fix xinfo() parameter definition

### PR DESCRIPTION
**Pull request by Yurunsoft**

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@Yurunsoft don't change arginfo.h files directly. You should update stub files and re-generate arginfo

**Comment by yatsukhnenko** [comment]
`arg3` should be string and also there is `mkstream` boolean argument
https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L4125

**Comment by Yurunsoft** [comment]
I am modifying `xinfo`, the type of `arg3` is long.
https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L4174

**Comment by michael-grunder** [comment]
Closing this as I apparently caught it in #2015 as well

**Pull request closed without merging**
