### PR TITLE
Issue #2068

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Add FCALL/FCALL_RO commands

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder I've seen you comment about response formatter and we need to discuss how should it looks like.

**Comment by yatsukhnenko** [comment]
Also I can do (in separated PR) API changes for `EVAL` and friends to make them similar to `FCALL`

**Review by michael-grunder — APPROVED** [review]

**Comment by michael-grunder** [comment]
This looks good.

I recently implemented this as well.  Mine is exactly the same except for the optional function call:

```php
public function call(string $fn, array $keys = [], array $args = [], callable $fn = NULL): mixed
```

I'm not sure whether users will want to send in a user-defined context variable, but for now, my callback looks like this:

```php
function callback(mixed $response): mixed
```

It's nice for doing things like zipping keys and scores from a function call:

```php
$resp = $redis->fcall('my_hgetall', ['somehash'], [], function ($resp) {
    $kv = [];
    for ($i = 0; $i < count($resp); $i += 2) {
        $kv[$resp[$i]] = $resp[$i+1];
    }
    return $kv;
});

**Comment by yatsukhnenko** [comment]
Oh, my thought was about internal formatting functions and additional enum argument. You implementation is just a syntax sugar to write two operations in one line 🙂

**Comment by michael-grunder** [comment]
> Oh, my thought was about internal formatting functions and additional enum argument.

I think maybe we should do _both_. Something like "zip keys and scores" is so common we could just let the user specify some integer constant.  For more custom things though, a callback could be nice.

Passing a callback is especially nice within things like MULTI/EXEC, so you don't have to keep an index into which reply is from your function so you can then format it.

**Comment by yatsukhnenko** [comment]
@michael-grunder how did you handle `fcall` callback with `multi/pipeline` mode? We need to store callback somewhere an apply it after `exec`...

**Comment by michael-grunder** [comment]
I can add that functionality to this branch if you like.  It's not too difficult.

**Comment by yatsukhnenko** [comment]
Let's merge this PR as is and add functionality in separated PR 🙂

**Comment by michael-grunder** [comment]
Works for me

**Pull request merged**
