### PR TITLE
Refactor redis_session

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Use `redis_sock` to store `auth` and `prefix` for session.
Use `redis_sock_auth` insted of `redis_pool_member_auth`.

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@SkydiveMarius if I'm not mistaken you use phpredis for sessions. Could you test this changes?

**Comment by SkydiveMarius** [comment]
@yatsukhnenko Yes, you are right. I will prepare the rollout on our test environment and will reply as soon we have any feedback.

**Comment by yatsukhnenko** [comment]
> but I don't use sessions.

That's why I'm still waiting feedback from @SkydiveMarius :smile:

**Comment by yatsukhnenko** [comment]
@SkydiveMarius any news?

**Comment by SkydiveMarius** [comment]
Unfortunately our PHP version is not supported anymore by the extension, atleast on clusters which are using sessions.
Therefore we are unable to test the change. Sorry for that.

**Comment by yatsukhnenko** [comment]
@SkydiveMarius No problem. We will test on users in production as always :smile: 
> our PHP version is not supported anymore by the extension

You definitely should think about migrating to PHP7. Huge performance improvements and computing resources economy.

**Comment by michael-grunder** [comment]
> No problem. We will test on users in production as always 😄

Is there any other way to test?  🤣

**Pull request merged**
