### PR TITLE
add note for building on gentoo distro

### PR DESCRIPTION
**Pull request by pculka**
just a proposal, might save a few headaches eventually.

### CODE REVIEW

**Comment by steffenweber** [comment]
Helps to fix the following error:

```
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
Makefile:193: recipe for target 'redis.lo' failed
make: *** [redis.lo] Error 63
```

Thanks!

**Comment by lkraav** [comment]
Yep, this is correct.

**Comment by yatsukhnenko** [comment]
Gentoo users should use `emerge` for packages installation and `libtool: Version mismatch` error should be handled by `ebuild`

**Comment by lkraav** [comment]
> Gentoo users should use emerge for packages installation and libtool: Version mismatch error should be handled by ebuild

Yeah, true. Unfortunately this package's `php-7` bump lagged behind a long time and it was necessary to get the branch manually compiled to try things out.

**Pull request closed without merging**
