### PR TITLE
Missing arg_infos for API introspection

### PR DESCRIPTION
**Pull request by jpauli**
I think someone should review them all. There may be mistakes

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@jpauli, thank you for your work. We have already had [issue.1055](https://github.com/phpredis/phpredis/tree/issue.1055) branch for this. Could you rebase your changes on top of that branch?

**Comment by jpauli** [comment]
Done.

I just reviewed the diff. Got no more time to give to this PR , I'll let you review the arg infos

**Comment by yatsukhnenko** [comment]
@jpauli, I'm sorry, could you do rebasing again? I just rebased issue.1055 itself on top of develop branch

**Comment by yatsukhnenko** [comment]
I've merged branch issue.1055 so almost all changes from this PR already merged

**Pull request closed without merging**
