### PR TITLE
Issue #1668

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Sending AUTH+PING uniqid in pipeline and checking that response equals to uniqid

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder could you please take a look?

**Comment by michael-grunder** [comment]
Looks good at first glance.  I'm putting together a stress test locally, but it's always nice if we can get someone to test it in a more production like environment.

**Comment by yatsukhnenko** [comment]
@michael-grunder it seems that we will test this fix in production as always 😄

**Comment by michael-grunder** [comment]
I've been testing the feature locally via php-fpm by intentionally causing timeouts in addition to just killing TCP connections and it's working great.

If you don't mind, I just want to modify the challenge string so it's easier to search, and also to add random entropy at the end.  I can imagine situations where extremely high volume could generate the same `tv_sec` + `tv_usec` string.

**Comment by michael-grunder** [comment]
Merged into develop.  I think it's smart to let it stew for a decent amount of time in the develop branch before releasing an official version, even though the testing I've been doing has worked great.

Some random thoughts:

1.  Should this be configurable?  I kind of think no because people would turn it off and then open issues here when they encounter corrupted connections.
1.  We probably want to document this in detail so it's well understood.  I'm happy to write the docs.
1.  This feature means that we can't operate against a Redis version that can't take an argument to PING (meaning Redis < 3.0.0).  We might have to handle that somehow.

**Pull request merged**
