### PR TITLE
the element of z_seeds may be a reference on php7

### PR DESCRIPTION
**Pull request by janic716**
yesterday i used RedisCluster connect my redis cluser, code like this:
$hosts = [
"10.1.15.22:7100",
"10.1.15.22:7101",
];
array_walk($hosts, function(&$val) {
$val = trim($val);
});
$rc = new RedisCluster(null, $hosts, null, null, true);

this code runs normally on php5.x but error on php7.x, error info is:
PHP Fatal error: Uncaught RedisClusterException: Couldn't map cluster keyspace using any provided seed in /opt/php/test.php:14
Stack trace:
#0 /opt/php/test.php(14): RedisCluster->__construct(NULL, Array, NULL, NULL, true)
#1 {main}
thrown in /opt/php/test.php on line 14

tracing the source code of phpredis, i found the element of ht_seeds is a referent in function cluster_init_seeds on php7.x environment.

i fixed this problem and re-compiled the redis extension, and the code runs normally on php7

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@janic716, thank you for your RP. Could you rewrite code using `ZVAL_DEREF` macro?

**Comment by janic716** [comment]
sure, thanks for the tip

**Comment by yatsukhnenko** [comment]
@janic716 :+1: Could you also sqash your commits into one?

**Comment by janic716** [comment]
@yatsukhnenko ,  i tried to rebase last 3 commits to one , but  i dont know  whether it works ......
maybe my operation is not correct

**Comment by yatsukhnenko** [comment]
@janic716 I want you to make single commit

**Comment by janic716** [comment]
i'm so sorry, i made a mistake when sqashing my commits
i will close this pull request and create new one

**Pull request closed without merging**
