### PR TITLE
Fix #1056 failed test on 32bits

### LINKED ISSUE #1056: Failed tests for 32bits build
```
Note: these tests might take up to a minute. Don't worry :-)
Testing class Redis
testMinimumVersion         [PASSED]
testPing                   [PASSED]
testPipelinePublish        [PASSED]
testPubSub                 [PASSED]
testBitsets                
Warning: Redis::setBit() expects parameter 2 to be integer, float given in /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php on line 170

Warning: Redis::getBit() expects parameter 2 to be integer, float given in /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php on line 171
[FAILED]
testBitPos                 [PASSED]
test1000                   [PASSED]
testEcho                   [PASSED]
testErr                    [PASSED]
testSet                    [PASSED]
testExtendedSet            [PASSED]
testGetSet                 [PASSED]
testRandomKey              [PASSED]
testRename                 [PASSED]
testRenameNx               [PASSED]
testMultiple               [PASSED]
testMultipleBin            [PASSED]
testSetTimeout             [PASSED]
testExpireAt               [PASSED]
testSetEx                  [PASSED]
testPSetEx                 [PASSED]
testSetNX                  [PASSED]
testExpireAtWithLong       
Warning: Redis::setex() expects parameter 2 to be integer, float given in /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php on line 481
[FAILED]
testIncr                   
Warning: Redis::incrBy() expects parameter 2 to be integer, float given in /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php on line 518
[FAILED]
testIncrByFloat            [PASSED]
testDecr                   [PASSED]
testExists                 [PASSED]
testGetKeys                [PASSED]
testDelete                 [PASSED]
testType                   [PASSED]
testStr                    [PASSED]
testlPop                   [PASSED]
testrPop                   [PASSED]
testblockingPop            [PASSED]
testllen                   [PASSED]
testlPopx                  [PASSED]
testltrim                  [PASSED]
testSortPrefix             [PASSED]
testSortAsc                [PASSED]
testSortDesc               [PASSED]
testlGet                   [PASSED]
testlrem                   [PASSED]
testsAdd                   [PASSED]
testscard                  [PASSED]
testsrem                   [PASSED]
testsMove                  [PASSED]
testsPop                   [PASSED]
testsRandMember            [PASSED]
testSRandMemberWithCount   [PASSED]
testsismember              [PASSED]
testsmembers               [PASSED]
testlSet                   [PASSED]
testsInter                 [PASSED]
testsInterStore            [PASSED]
testsUnion                 [PASSED]
testsUnionStore            [PASSED]
testsDiff                  [PASSED]
testsDiffStore             [PASSED]
testlrange                 [PASSED]
testdbSize                 [PASSED]
testttl                    [PASSED]
testPersist                [PASSED]
testClient                 [PASSED]
testSlowlog                [PASSED]
testWait                   [PASSED]
testInfo                   [PASSED]
testInfoCommandStats       [PASSED]
testSelect                 [PASSED]
testMset                   [PASSED]
testMsetNX                 [PASSED]
testRpopLpush              [PASSED]
testBRpopLpush             [PASSED]
testZAddFirstArg           [PASSED]
testZX                     [PASSED]
testHashes                 
Warning: Redis::hIncrBy() expects parameter 3 to be integer, float given in /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php on line 2299
[FAILED]
testSetRange               [PASSED]
testObject                 [PASSED]
testMultiExec              [PASSED]
testFailedTransactions     [PASSED]
testPipeline               [PASSED]
testDifferentTypeString    [PASSED]
testDifferentTypeList      [PASSED]
testDifferentTypeSet       [PASSED]
testDifferentTypeSortedSet [PASSED]
testDifferentTypeHash      [PASSED]
testSerializerPHP          [PASSED]
testSerializerIGBinary     [PASSED]
testDumpRestore            [PASSED]
testGetLastError           [PASSED]
testScript                 [PASSED]
testEval                   [PASSED]
testEvalSHA                [PASSED]
testSerialize              [PASSED]
testUnserialize            [PASSED]
testPrefix                 [PASSED]
testReconnectSelect        [PASSED]
testTime                   [PASSED]
testReadTimeoutOption      [PASSED]
testIntrospection          [PASSED]
testScan                   [PASSED]
testHScan                  [PASSED]
testSScan                  [PASSED]
testZScan                  [PASSED]
testPFCommands             [PASSED]
testGeoAdd                 [PASSED]
testGeoRadius              [PASSED]
testGeoRadiusByMember      [PASSED]
testGeoPos                 [PASSED]
testGeoHash                [PASSED]
testGeoDist                [PASSED]
testRawCommand             [PASSED]


Assertion failed (1 !== ): /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php:171 (testBitsets)
Assertion failed: /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php:481 (testExpireAtWithLong)
Assertion failed: /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php:482 (testExpireAtWithLong)
Assertion failed (2147483648 !== ): /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php:518 (testIncr)
Assertion failed: /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php:2299 (testHashes)
Assertion failed: /builddir/build/BUILD/php-pecl-redis-3.1.0/NTS/tests/RedisTest.php:2300 (testHashes)

```

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by remicollet** [comment]
Still 1 failure on armv7hl
`
Assertion failed (1.8 !== 1.80000000000000004): /builddir/build/BUILD/php-pecl-redis-3.1.1/NTS/tests/RedisTest.php:556 (testIncrByFloat)
`
Working on it

**Comment by remicollet** [comment]
Everything seems ok now.

See https://koji.fedoraproject.org/koji/taskinfo?taskID=17024279 (i686, x86_64, ppc64, ppc64le, armv7hl, aarch64)

**Comment by yatsukhnenko** [comment]
@remicollet, any chance to receive access to your building environment for testing new features of phpredis?

**Comment by remicollet** [comment]
@yatsukhnenko this is the Fedora build system used by Fedora package maintainers.

BTW, you can probably use [Copr](https://copr.fedorainfracloud.org/) which is specially design for upstream projects.

In all case, only RPM build are supported.

**Comment by michael-grunder** [comment]
Thanks!

**Pull request merged**
