### PR TITLE
Explain that `delete` is now deprecated

### PR DESCRIPTION
**Pull request by ruudk**
Couldn't find it anywhere.

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@ruudk all aliases are deprecated.
This change is [mentioned](https://pecl.php.net/package-info.php?package=redis&version=5.0.0) in Changelog on PECL

**Comment by ruudk** [comment]
Oke, maybe good to add that here? https://github.com/phpredis/phpredis/blob/develop/Changelog

**Comment by yatsukhnenko** [comment]
All future changes will be added there :)

**Comment by ruudk** [comment]
Can we please add this to the current changelog? This will make it easier for every developer that stumbles on these deprecations. I never see the PECL website so wasn't aware of this:

* Add changelog to the Github release https://github.com/phpredis/phpredis/releases/tag/5.0.0
* Add it to the Changelog.md file that everyone is going to click on

**Comment by Kakashi-sempai** [comment]
This is a good website

**Comment by yatsukhnenko** [comment]
https://github.com/phpredis/phpredis/blob/develop/Changelog.md#deprecated

**Comment by Norgul** [comment]
What are repercussions of using a deprecated method here? I am getting the error in my prod environment, but coming up as a notice. Should it break something up to the point where it is no longer supported?

**Comment by yatsukhnenko** [comment]
All deprecated methods will be removed in next major release.

**Comment by Norgul** [comment]
But using the current release it should not fail, but just give out notice?

**Comment by michael-grunder** [comment]
Yes, for PhpRedis 5.x it will just show the warning but the command will work just fine.

We removed them because there were several old aliases for commands that don't actually correspond to an actual Redis command (e.g. there is no `DELETE` command in Redis, only `DEL`)

**Pull request closed without merging**
