### PR TITLE
MOD: Support reply literal string instead of bool when redis reply simple string

### PR DESCRIPTION
**Pull request by git-hulk**
The Redis simple string was converted to true in `redis_read_variant_line`, but sometimes we need to get the string. 

for example, we use phpredis  to connect the Disque, execute the `ADDJOB` by rawCommand, and it should retrieve the `job id`(simple string like "+D-b628d44e-i7UHxyLPj2aPT3BPD3VPz4P2-05a1") but got TRUE.

We should retrieve the simple string instead of TRUE, while it may mean to user

### CODE REVIEW

**Comment by michael-grunder** [comment]
Hey,

Thanks for the pull request but we probably can't just blanket change the return type for status replies without breaking the API for people but I do see what you're trying to do here.

This functionality could be provided in a couple of ways.  There could be a non default option for the Redis class to return the literal string response for simple string replies, or an additional `rawCommand` like command that didn't treat any `+` reply as a simple boolean but returned the string instead.

**Comment by git-hulk** [comment]
@michael-grunder Got what you mean, it's much better that didn't treat any `+` reply as simple boolean but returned the string instead. I'll fix it now.

**Comment by git-hulk** [comment]
Hello, @michael-grunder, can you review the pr again? 

I fix it by adding the `OPT_REPLY_LITERAL` option, while return literal string only in rawCommand may cause duplicated code. And this option wasn't supported in RedisCluster.

**Comment by git-hulk** [comment]
@michael-grunder Can you review this pr, we would like this feature very much.

**Comment by michael-grunder** [comment]
Hi,

This looks OK to me on first glance.  I'll build the change locally and play around with it.  

Incidentally the tests show as failing because Travis can't find the PHP 5.3 bzip file so perhaps they've removed it (it sure is old enough).

@yatsukhnenko Any thoughts on the functionality?  I suppose for consistency we could return the literal for any command if the option is set, but I can't think of any Redis proper command where it would be needed so it seems OK to limit the change to `rawCommand`.

**Comment by yatsukhnenko** [comment]
@michael-grunder, this looks like a crutch :smile:

**Comment by michael-grunder** [comment]
The functionality is just so that people can get the Redis string response if they want it.  It doesn't make a lot of sense for vanilla Redis but in this example it's useful for a Disque reply and it might also be useful in the context of a Redis module.

We can't add an additional argument to `rawCommand` because that's already variadic.  I suppose we could create something like `rawCommandArray` that looked like this:

```function rawCommandArray($str_cmd_name, $arr_arguments, $boo_return_literal = false)```

That might be a little cleaner than adding an option just for this really unique use case.  I'm not sure if it is still the case but it used to be that functions taking an array were quite a bit faster than variadic functions (when you called them via `call_user_func_array` anyway).

**Comment by git-hulk** [comment]
@michael-grunder  Since `+` in Redis's semantic is a simple string, not bool, so it makes sense to return the string for any commands.

**Comment by git-hulk** [comment]
@michael-grunder Any thoughts on how to fix this problem? I also insist should reply simple string in all instead of in `raw command`.

By the way, maybe I should change code base to develop(current is master).

**Comment by michael-grunder** [comment]
Hi,

I'm closing this pull request because I have cherry-picked the commits and placed them into a local branch [here](https://github.com/phpredis/phpredis/tree/string-reply-literal).  Now the question is whether we'll want that option to apply only to `rawCommand` or to _every_ command.

**Pull request closed without merging**
