### PR TITLE
Issue #2106

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by tillkruss** [comment]
How would this work with Redis cluster?

Sentinel should just work since they use regular Redis connections.

**Comment by michael-grunder** [comment]
@tillkruss I think we'd need to add a method on RedisCluster to do some kind of `SUM(txBytes)` across each internal `RedisSock`, but that's probably pretty straightforward.

**Comment by tillkruss** [comment]
@michael-grunder: Any preferences on how @yatsukhnenko does it?

**Comment by michael-grunder** [comment]
No not really.  I don't mind adding it either.

**Comment by yatsukhnenko** [comment]
@tillkruss @michael-grunder It might be `SUM(txBytes)` but this means I have to clear this value on all nodes before sending any request.

**Comment by yatsukhnenko** [comment]
@tillkruss Also should we count all transferred bytes when redirection occurs?

**Comment by tillkruss** [comment]
I'd say no, but I leave that up to @michael-grunder to decide.

**Comment by yatsukhnenko** [comment]
@michael-grunder we need your thoughts about implementation

**Comment by yatsukhnenko** [comment]
@michael-grunder could you take a look, please

**Comment by michael-grunder** [comment]
Yes, I will look first thing in the morning.

**Comment by michael-grunder** [comment]
> Also should we count all transferred bytes when redirection occurs?

I tend to think we should count those bytes if the purpose of the metrics is to keep track of how much data PhpRedis is actually sending over the wire.  Redirections involve more network traffic.

> It might be SUM(txBytes) but this means I have to clear this value on all nodes before sending any request.

Maybe we could just accumulate the totals and give the users an option to reset the value arbitrarily.  It's not likely a slow operation but it could be noticeable if we did it automatically after every command (especially with lots of nodes).

**Comment by tillkruss** [comment]
>and give the users an option to reset the value arbitrarily

I was thinking that either calling `getTransferredBytes()` should reset the counter, or provide a dedicated method.

**Comment by michael-grunder** [comment]
@yatsukhnenko We can merge this and then figure out how to make it work for Redis Cluster later if you like.

**Comment by yatsukhnenko** [comment]
@michael-grunder no, I'm going to finish this tomorrow

**Comment by yatsukhnenko** [comment]
> @michael-grunder no, I'm going to finish this tomorrow

:angry: funcking russians with their missles...

**Comment by yatsukhnenko** [comment]
@michael-grunder it is ready for review.
I probably missed something and in some cases it would returns wrong value :smiling_face_with_tear: 
Also I found many places in `cluster_library.c` which I want to refactor :smile:

**Review by michael-grunder — APPROVED** [review]

**Comment by michael-grunder** [comment]
@yatsukhnenko Let's merge it so @tillkruss can try it out.  I think maybe at some point we'll add `rxBytes` too?

> Also I found many places in cluster_library.c which I want to refactor 

But why?  All of that code is perfect 😂

**Pull request merged**
