### PR TITLE
bugfix 718

### PR DESCRIPTION
**Pull request by mixiaojiong**
https://github.com/phpredis/phpredis/issues
i fix it.
I submit this is absolutely from the latest version.

### CODE REVIEW

**Comment by mixiaojiong** [comment]
I submitted again

**Comment by michael-grunder** [comment]
I cherry-picked 7c868dc into the `develop` and `php7` branches, so they are in there.

Cheers!
Mike

**Comment by mixiaojiong** [comment]
Thanks for your help, I learned a lot.

2016年1月13日星期三，Michael Grunder <notifications@github.com> 写道：

**Comment by michael-grunder** [comment]
No thank you, it was a good find!  :smiley_cat:

**Pull request closed without merging**
