### PR TITLE
integer_length optimization

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Based on the [article](https://www.facebook.com/notes/facebook-engineering/three-optimization-tips-for-c/10151361643253920)

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder, what do you think? Redis also uses similar technique

**Comment by michael-grunder** [comment]
Brilliant.  

Feel free to merge any changes like this on your own especially now that we have automated testing hooked in.

Besides, they're develop versions for a reason and I *promise* users will let us know if anything breaks! 😀

**Comment by yatsukhnenko** [comment]
@michael-grunder, do you have any ideas what should be firstly improved in phphedis but you don't have enough time to work over it?

**Comment by HansVanEijsden** [comment]
Thanks for all the work, but unfortunately this seems to break compiling for me.
Details: https://github.com/phpredis/phpredis/issues/929

**Pull request merged**
