### PR TITLE
Add support to RedisCluster password

### PR DESCRIPTION
**Pull request by zhengide**
Based on #902 and branch develop.
Resolve conflicts and add support to session.
Please review and merge.

### CODE REVIEW

**Comment by michael-grunder** [comment]
Awesome!  I'll go over this in the next couple days and then get it merged before our next release.

**Comment by michael-grunder** [comment]
Hey, thanks for adding this feature!

I've merged this code into a branch here:
https://github.com/phpredis/phpredis/tree/cluster-auth

I'll do a bit of testing locally but then I think we can get it merged.  

@yatsukhnenko Any reason not to merge into develop?

**Comment by yatsukhnenko** [comment]
@michael-grunder I remember that you had an objection about storing password in ini file :)
I do have two reasons to not merge this PR as is:
1. Now we use `zend_string` instead of `char *` + `size_t` for storing settings
2. I'm not sure about idea but would it be useful to set different passwords for each cluster node? Should we discuss this?

**Comment by yatsukhnenko** [comment]
@michael-grunder since you merged code to the repo I will fix my first note :)

**Comment by michael-grunder** [comment]
Ahh, that's right.

We should make sure to use `zend_string` for the settings for sure.

As for different passwords I'm not sure how we would go about that.  It does seem somewhat complicated.  I suppose we could allow for the password to be provided per-seed, _or_ for one auth argument which would be treated as global.

**Comment by yatsukhnenko** [comment]
Also there is an implicit declaration of function
```
In file included from /home/pyatsukhnenko/code/phpredis/redis_commands.h:6:0,
                 from /home/pyatsukhnenko/code/phpredis/cluster_library.c:4:
/home/pyatsukhnenko/code/phpredis/cluster_library.c: In function ‘cluster_send_direct’:
/home/pyatsukhnenko/code/phpredis/cluster_library.h:71:13: warning: implicit declaration of function ‘resend_auth’ [-Wimplicit-function-declaration]
             resend_auth(s TSRMLS_CC);\
             ^
/home/pyatsukhnenko/code/phpredis/cluster_library.c:262:5: note: in expansion of macro ‘CLUSTER_LAZY_CONNECT’
     CLUSTER_LAZY_CONNECT(redis_sock);
     ^~~~~~~~~~~~~~~~~~~~
```

**Comment by yatsukhnenko** [comment]
I pushed changes for zend_string auth.

> It does seem somewhat complicated

I don't know will it be useful at all. Probably we don't need to do password per-seed until somebody will ask about this feature :)

**Pull request closed without merging**
