### PR TITLE
use PHP_BINARY instead of php and allow override

### PR DESCRIPTION
**Pull request by remicollet**
exec("php ...")  seems a bad idea.

Can be something different according to install options
More we may need to pass some options to enable the newly built extension

With this PR, current behavior is preserved (and slightly improved)
And we can override its value

Usage example:

```
export TEST_PHP_EXECUTABLE=/path/to/php
export TEST_PHP_ARGS="-n -d extension=igbinary.so -d extension=$PWD/modules/redis.so"
$TEST_PHP_EXECUTABLE $TEST_PHP_ARGS  tests/TestRedis.php
Note: these tests might take up to a minute. Don't worry :-)
Using PHP version 7.1.18 (64 bits)
/modules/redis.so
Testing class Redis
testMinimumVersion                                             [PASSED]
testPing                                                       [PASSED]
....
testSession_ttl_resetOnRead                                    [PASSED]

Skipped test: /work/GIT/phpredis/tests/RedisTest.php:4312 (testCompressionLZF) 

All tests passed. \o/

```

### CODE REVIEW

**Comment by remicollet** [comment]
Notice that for such needs, run-test.php (from php) and .phpt tests are better, thanks to `TEST_PHP_ARGS `and `TEST_PHP_EXECUTABLE` variable.

**Comment by yatsukhnenko** [comment]
Thanks @remicollet!
This solution doesn't work on 5.3 because PHP_BINARY is not defined.
I'm not sure we will drop support 5.3 for this reason so I can't merge this PR as is :)

**Comment by remicollet** [comment]
Fully rewritten and factorized

**Comment by remicollet** [comment]
And travis seems happy \p/

**Comment by yatsukhnenko** [comment]
Thanks @remicollet :+1:

**Pull request merged**
