### PR TITLE
missing EXTENSION directive

### PR DESCRIPTION
**Pull request by pierrejoye**
First fix to restore Windows support.

By the way, what do you think about merging php 5&7 in one branch and two separate folders:
- php5
- php7
- config.m4
- config.w32
- readme...
  etc...

Doing so will allow cleaner versioning and support for semver. That will also make it very easy for build automation and release under pickle/composer (or existing pecl).

I can prepare a PR to do it if you like to, that would be awesome.

### CODE REVIEW

**Comment by pierrejoye** [comment]
Also fixed the build now while being at it.

Mainly invalid declarations (php 5.x does not support c99)

**Comment by michael-grunder** [comment]
I quite like your idea of merging the php7 code into develop this way.  Ideally I would love to have just one branch but that will take ages to complete properly.

I think that would be a good solution for the next release.

I'll see about getting this and your other pull request merged and then hopefully we can get some people who have windows machines to verify that it works properly (being full hipster I don't have a windows box) :)

Mike

**Comment by pierrejoye** [comment]
hi,

Thanks for looking at these PRs :)

Let me know (or I will see the notifications :) and I can do a PR to create
one branch for both. Maybe keep master for that then?

I could do it this week still :)

Thanks for your work!

On Wed, Mar 16, 2016 at 12:37 AM, Michael Grunder <notifications@github.com>
wrote:

> I quite like your idea of merging the php7 code into develop this way.
> Ideally I would love to have just one branch but that will take ages to
> complete properly.
>
> I think that would be a good solution for the next release.
>
> I'll see about getting this and your other pull request merged and then
> hopefully we can get some people who have windows machines to verify that
> it works properly (being full hipster I don't have a windows box) :)
>
> Mike
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phpredis/phpredis/pull/758#issuecomment-196941001>
>



-- 
Pierre

@pierrejoye | http://www.libgd.org

**Comment by yatsukhnenko** [comment]
@pierrejoye, could you squash your commits into one and rebase it onto `develop` brunch?

**Comment by pierrejoye** [comment]
Is it not possible to do that in GitHub directly now? The squash part.

Also I won't have the time until December to sync this patch with another
branch.

Cheers

**Comment by yatsukhnenko** [comment]
@michael-grunder do we need this chances?

**Comment by yatsukhnenko** [comment]
Probably no. Reopen if I'm wrong.

**Pull request closed without merging**
