### PR TITLE
LMPOP and ZMPOP commands

### PR DESCRIPTION
**Pull request by michael-grunder**

### CODE REVIEW

**Comment by michael-grunder** [comment]
@yatsukhnenko Do you think I should create a custom `zmpop` handler to zip keys and scores?

**Comment by yatsukhnenko** [comment]
@michael-grunder since `lmpop` and `zmpop` return a two-element array I think it would be better to zip results

**Comment by michael-grunder** [comment]
I will fix the cluster handler tomorrow

**Comment by michael-grunder** [comment]
@yatsukhnenko OK the overall logic is ready for review now.

**Review by yatsukhnenko — APPROVED** [review]

**Pull request merged**
