### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by GDdark**
Update the part of doc about exists

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@GDdark, thank you for your PR but it fits to `develop` but not `3.1.4RC3` branch

**Comment by GDdark** [comment]
@yatsukhnenko OK! I have changed the base

**Comment by yatsukhnenko** [comment]
Now you try to merge changes from 3.1.4RC3

**Comment by yatsukhnenko** [comment]
@GDdark you should rebase your commit onto the head of `develop` branch

**Pull request closed without merging**
