### PR TITLE
Issue #1523

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Add server address to exception message.

### CODE REVIEW

**Comment by michael-grunder** [comment]
This seems fine, but we should probably try to give people a head's up about it:
https://github.com/search?l=PHP&p=1&q=%22read+error+on+connection%22&type=Code

**Comment by yatsukhnenko** [comment]
@michael-grunder what if we will add server address to all exceptions and add the notice to documentation that all exceptions ware changed?

**Comment by yatsukhnenko** [comment]
Also there may be different code for every exception (now zero is everywhere) so users will not need to compare exception messages.

**Comment by michael-grunder** [comment]
Yeah unique error codes are probably useful too.

We're allowed to break things for 5.0.0 but if we can let downstream users know they'd probably appreciate it.

On the other hand they might just completely ignore any warnings until they upgrade and then come yell at us.  🤣

**Pull request merged**
