### PR TITLE
WIP for 875 on php7

### PR DESCRIPTION
**Pull request by vamage**
Adding checking to make sure we don't close the stream  #965   Tested with:

```
<?php
//step 1
try{
    $redis1 = testRedis();
    if($redis1) {
        var_dump($redis1->get('xiyuan_test1'));
        echo "\n";
    }
}catch(\RedisException $e){
    echo 'redis error1: errno='.$e->getCode().' errmsg='.$e->getMessage()."\n";
}

//step 2
try{
    $redis2 = testRedis();
    sleep(10);
    if($redis2) {
        var_dump($redis2->get('xiyuan_test2'));   //  kill redis-server(/home/redis/bin/redis-server /home/redis/redis.conf && sleep 5 && ps -ef |grep redis |awk '{print $2}'|xargs kill -9) , force redis connection lost .
        echo "\n";
    }
}catch(\RedisException $e){
    echo 'redis error2: errno='.$e->getCode().' errmsg='.$e->getMessage()."\n";
}

//step 3
try{
    if($redis1){
        var_dump($redis1->get('xiyuan_test3'));  // at this line , core 
        echo "\n";
    }
}catch(\RedisException $e){
    echo 'redis error3: errno='.$e->getCode().' errmsg='.$e->getMessage()."\n";
}

function testRedis($ip='127.0.0.1',$port=6379,$timeout=0,$index=0){
    try{
        $instance = new \Redis();
        $instance->pconnect($ip, $port, $timeout);
        if($instance->select($index)){
            return $instance;
        }
    }catch(\RedisException $e){
        echo 'redis error4: errno='.$e->getCode().' errmsg='.$e->getMessage()."\n";
        return false;
    }
}
```

Output

```
 php redis.php
bool(false)

redis error2: errno=0 errmsg=Connection lost
redis error3: errno=0 errmsg=Connection lost
```

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@vamage, please squash all your commits into one and rename onto head of develop brunch if needed

**Comment by ovr** [comment]
ping @yatsukhnenko can you take a look?

**Comment by yatsukhnenko** [comment]
@vamage, your fix is not compatible with older versions of php.

**Comment by vamage** [comment]
I'll take a look at that this week. I thought it was breaking on something else in devel.

**Comment by vamage** [comment]
This looks to build on centos7 armv7 php56
I'll need to set up a box to match  travisci to debug a bit further.

**Comment by ovr** [comment]
@vamage 

> /home/travis/build/phpredis/phpredis/library.c:97:5: error: too few arguments to function ‘php_stream_from_persistent_id’

PHP 5 https://github.com/php/php-src/blob/PHP-5.6/main/php_streams.h#L266
image

PHP 7+ https://github.com/php/php-src/blob/PHP-7.0/main/php_streams.h#L278
image

IMHO, you PHP 5, requires TSRMLS_DC as 3d parameter, you should pass TSRMLS_CC if it's PHP5

What do you think about it?

Thanks

**Comment by yatsukhnenko** [comment]
@vamage, @michael-grunder I guess this isn't relevant anymore because we have proper connection pooling

**Comment by vamage** [comment]
let me close it then

**Pull request closed without merging**
