### PR TITLE
Issue #1894

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Add the CH, NX, XX arguments to GEOADD

### CODE REVIEW

**Comment by michael-grunder** [comment]
I looked at adding this a while back and realized it was a bit tricky.

These changes would break all existing uses of `GEOADD` so it makes me pretty nervous.  It's a big ugly but we could infer the options by allowing the first argument to be `float|array`, and then calculate based on that.

**Comment by yatsukhnenko** [comment]
@michael-grunder I thought about this but it was looking really ugly. What if we add `options` to the end of the arguments list?

**Comment by michael-grunder** [comment]
Both seem ugly to me, so if you prefer putting the options at the end that's fine with me.  :smile:

**Comment by yatsukhnenko** [comment]
With `options` at the end it would be similar to `georadius`, `geosearch`, etc

**Comment by yatsukhnenko** [comment]
Now the change doesn't break backward compatibility :smiley:

**Review by michael-grunder — APPROVED** [review]

**Pull request merged**
