### PR TITLE
Json msgpack

### PR DESCRIPTION
**Pull request by crodas**
Added serializers for JSON and MSGPACK.

### CODE REVIEW

**Comment by cola1129** [comment]
Why not these serializers? It is very useful for developing with multiple program languages!

**Comment by crodas** [comment]
@cola1129, @nicolasff, @michael-grunder I can merge master against this pull request and update tests if it worth it.

Cheers,

**Comment by trompx** [comment]
Is it still considered to merge this ? I'd be interested to use msgpack as serializer. Any idea if the hIncrBy function will work out of the box unlike with igbinary serializer ?
Thanks

**Comment by razvanphp** [comment]
Any news on this? With igbinary support for php7 very limited, failed tests and buggy + GA launch in 10 days, we have no real option other than msgpack.

@crodas maybe you should fix the conflicts, so that merging can be considered by the maintainers.

**Comment by crodas** [comment]
@razvanphp I'll resolve the conflicts either today or tomorrow.

**Comment by razvanphp** [comment]
@crodas ping!

**Comment by peterbowey** [comment]
@crodas
@razvanphp  @trompx @cola1129, @nicolasff, @michael-grunder

PHP7 + MSGPACK

I have merged the pull (above patches) from https://github.com/phpredis/phpredis/pull/404#issue-22284988 to work with the current php7 branch; git clone -b php7 https://github.com/phpredis/phpredis.git

Notes:  In the following patch, I dropped the above serializer for JSON and worked only on the on the MSGPACK serializer code. (not have enough time or motivation to do the JSON part - yet).

As the current github igbinary php7 pull is still rather 'buggy', I was keen to see what MSGPACK could do (to replace https://github.com/igbinary/igbinary/tree/php7-dev, or https://github.com/igbinary/igbinary/tree/php7-dev-playground1 and https://github.com/igbinary/igbinary/tree/php7-dev-playground2).

Patch begins:
__________
```
diff --git a/phpredis/common.h b/phpredis/common.h
--- a/phpredis/common.h	2015-12-12 19:20:34.075779598 +1030
+++ b/phpredis/common.h	2015-12-12 14:35:20.000000000 +1030
@@ -75,6 +75,7 @@
 #define REDIS_SERIALIZER_NONE        0
 #define REDIS_SERIALIZER_PHP         1
 #define REDIS_SERIALIZER_IGBINARY    2
+#define REDIS_SERIALIZER_MSGPACK     3
 
 /* SCAN options */
 #define REDIS_SCAN_NORETRY 0
diff --git a/phpredis/config.m4 b/phpredis/config.m4
--- a/phpredis/config.m4	2015-12-12 19:20:34.075779598 +1030
+++ b/phpredis/config.m4	2015-12-12 14:47:10.000000000 +1030
@@ -11,6 +11,9 @@
 PHP_ARG_ENABLE(redis-igbinary, whether to enable igbinary serializer support,
 [  --enable-redis-igbinary      Enable igbinary serializer support], no, no)
 
+PHP_ARG_ENABLE(msgpack, whether to enable msgpack serializer support,
+[  --enable-msgpack Include msgpack support], no, no)
+
 
 if test "$PHP_REDIS" != "no"; then
 
@@ -85,7 +88,7 @@
 
   dnl # --with-redis -> check for lib and symbol presence
   dnl LIBNAME=redis # you may want to change this
-  dnl LIBSYMBOL=redis # you most likely want to change this 
+  dnl LIBSYMBOL=redis # you most likely want to change this
 
   dnl PHP_CHECK_LIBRARY($LIBNAME,$LIBSYMBOL,
   dnl [
@@ -100,4 +103,11 @@
   dnl PHP_SUBST(REDIS_SHARED_LIBADD)
 
   PHP_NEW_EXTENSION(redis, redis.c redis_commands.c library.c redis_session.c redis_array.c redis_array_impl.c redis_cluster.c cluster_library.c, $ext_shared)
+  if test "$PHP_MSGPACK" != "no"; then
+    AC_DEFINE(HAVE_MSGPACK,1,[enable msgpack])
+        ifdef([PHP_ADD_EXTENSION_DEP],
+        [
+            PHP_ADD_EXTENSION_DEP(redis, msgpack, true)
+        ])
+  fi
 fi
diff --git a/phpredis/library.c b/phpredis/library.c
--- a/phpredis/library.c	2015-12-12 19:20:34.077779630 +1030
+++ b/phpredis/library.c	2015-12-12 17:25:55.000000000 +1030
@@ -1398,7 +1398,6 @@
         zval z;
         if(redis_unserialize(redis_sock, response, response_len, &z) == 1)
         {
-            efree(response);
             add_next_index_zval(z_tab, &z);
         } else {
             add_next_index_stringl(z_tab, response, response_len);
@@ -1407,11 +1406,10 @@
         if(redis_unserialize(redis_sock, response, response_len,
                              return_value TSRMLS_CC) == 0)
         {
-            RETURN_STRINGL(response, response_len);
-        } else {
-            efree(response);
+            RETVAL_STRINGL(response, response_len);
         }
     }
+    efree(response);
 }
 
 /* like string response, but never unserialized. */
@@ -1918,11 +1916,11 @@
         if(response != NULL) {
             zval z;
             if(redis_unserialize(redis_sock, response, response_len, &z) == 1) {
-                efree(response);
                 add_assoc_zval_ex(&z_multi_result, Z_STRVAL(z_keys[i]), Z_STRLEN(z_keys[i]), &z);
             } else {
                 add_assoc_stringl_ex(&z_multi_result, Z_STRVAL(z_keys[i]), Z_STRLEN(z_keys[i]), response, response_len);
             }
+            efree(response);
         } else {
             add_assoc_bool_ex(&z_multi_result, Z_STRVAL(z_keys[i]), Z_STRLEN(z_keys[i]), 0);
         }
@@ -2017,9 +2015,10 @@
 
             /* return string */
             convert_to_string(&z_copy);
-            *val = Z_STRVAL_P(&z_copy);
+            *val = estrndup(Z_STRVAL_P(&z_copy), Z_STRLEN_P(&z_copy));
             *val_len = Z_STRLEN_P(&z_copy);
-            return 0;
+            zval_ptr_dtor(&z_copy);
+            return 1;
 
         case REDIS_SERIALIZER_PHP:
 
@@ -2031,6 +2030,16 @@
 
             return 0;
 
+        case REDIS_SERIALIZER_MSGPACK:
+#if HAVE_MSGPACK
+            php_msgpack_serialize(&sstr, z TSRMLS_CC);
+            *val = sstr.s->val;
+            *val_len = sstr.s->len;
+
+            return 0;
+#endif
+            return 0;
+
         case REDIS_SERIALIZER_IGBINARY:
 #ifdef HAVE_REDIS_IGBINARY
             if(igbinary_serialize(&val8, &sz, z TSRMLS_CC) == 0) {
@@ -2067,6 +2076,13 @@
             PHP_VAR_UNSERIALIZE_DESTROY(var_hash);
             return ret;
 
+        case REDIS_SERIALIZER_MSGPACK:
+#if HAVE_MSGPACK
+            php_msgpack_unserialize(return_value, val, val_len TSRMLS_CC);
+            return 1;
+#endif
+            return 0;
+
         case REDIS_SERIALIZER_IGBINARY:
 #ifdef HAVE_REDIS_IGBINARY
             if(igbinary_unserialize((const uint8_t *)val, (size_t)val_len,
diff --git a/phpredis/redis.c b/phpredis/redis.c
--- a/phpredis/redis.c	2015-12-12 19:20:34.079779661 +1030
+++ b/phpredis/redis.c	2015-12-12 14:42:36.000000000 +1030
@@ -343,8 +343,20 @@
      {NULL, NULL, NULL}
 };
 
+#if ZEND_MODULE_API_NO >= 20050922
+zend_module_dep redis_deps[] = {
+#ifdef HAVE_MSGPACK
+    ZEND_MOD_REQUIRED("msgpack")
+#endif
+    {NULL, NULL, NULL}
+};
+#endif
+
 zend_module_entry redis_module_entry = {
-#if ZEND_MODULE_API_NO >= 20010901
+#if ZEND_MODULE_API_NO >= 20050922
+     STANDARD_MODULE_HEADER_EX, NULL,
+     redis_deps,
+#else
      STANDARD_MODULE_HEADER,
 #endif
      "redis",
@@ -522,6 +534,9 @@
         zend_declare_class_constant_long(ce, ZEND_STRL("FAILOVER_ERROR"), REDIS_FAILOVER_ERROR TSRMLS_CC);
         zend_declare_class_constant_long(ce, ZEND_STRL("FAILOVER_DISTRIBUTE"), REDIS_FAILOVER_DISTRIBUTE TSRMLS_CC);
     }
+#if HAVE_MSGPACK
+    zend_declare_class_constant_long(ce, ZEND_STRL("SERIALIZER_MSGPACK"), REDIS_SERIALIZER_MSGPACK TSRMLS_CC);
+#endif
 #ifdef HAVE_REDIS_IGBINARY
     zend_declare_class_constant_long(ce, ZEND_STRL("SERIALIZER_IGBINARY"), REDIS_SERIALIZER_IGBINARY TSRMLS_CC);
 #endif
diff --git a/phpredis/redis_commands.c b/phpredis/redis_commands.c
--- a/phpredis/redis_commands.c	2015-12-12 19:20:34.081779693 +1030
+++ b/phpredis/redis_commands.c	2015-12-12 14:43:47.000000000 +1030
@@ -2922,6 +2922,9 @@
         case REDIS_OPT_SERIALIZER:
             val_long = atol(val_str);
             if(val_long == REDIS_SERIALIZER_NONE
+#ifdef HAVE_MSGPACK
+                || val_long == REDIS_SERIALIZER_MSGPACK
+#endif
 #ifdef HAVE_REDIS_IGBINARY
                 || val_long == REDIS_SERIALIZER_IGBINARY
 #endif
diff --git a/phpredis/tests/RedisTest.php b/phpredis/tests/RedisTest.php
--- a/phpredis/tests/RedisTest.php	2015-12-12 19:20:34.084779740 +1030
+++ b/phpredis/tests/RedisTest.php	2015-12-12 14:48:29.000000000 +1030
@@ -1,4 +1,4 @@
-<?php defined('PHPREDIS_TESTRUN') or die("Use TestRedis.php to run tests!\n"); 
+<?php defined('PHPREDIS_TESTRUN') or die("Use TestRedis.php to run tests!\n");
 
 require_once(dirname($_SERVER['PHP_SELF'])."/TestSuite.php");
 
@@ -2414,7 +2414,7 @@
 
     public function testFailedTransactions() {
         $this->redis->set('x', 42);
-    
+
         // failed transaction
         $this->redis->watch('x');
 
@@ -2539,7 +2539,7 @@
             ->ttl('key')
             ->expireAt('key', '0000')
             ->exec();
-        
+
         $this->assertTrue(is_array($ret));
         $i = 0;
         $ttl = $ret[$i++];
@@ -4393,6 +4393,9 @@
         if(defined('Redis::SERIALIZER_IGBINARY')) {
             $serializers[] = Redis::SERIALIZER_IGBINARY;
         }
+        if(defined('Redis::SERIALIZER_MSGPACK')) {
+        		$serializers[] = Redis::SERIALIZER_MSGPACK;
+        }
 
         foreach($serializers as $mode) {
             $vals_enc = Array();

```

Please note that the above patch includes pull 700 for memory leaks on the php7 branch. See: https://github.com/phpredis/phpredis/pull/700 for memory leaks.

The above patch passes all the tests in TestRedis.php
All tests passed. \o/

**Comment by razvanphp** [comment]
Why posting this as a patch and not a real pull request?

**Comment by peterbowey** [comment]
@razvanphp 
Simply, it saves some time (for me)!
Otherwise, I would need time to raise over 100 pull requests.. (issues / patches) in the last few months.

**Comment by razvanphp** [comment]
Well, this is not how GitHub works unfortunately... all of us should benefit from this, with a well tested, properly merged feature. I still think for this the first step would be so that @crodas fixes the merge conflicts.

**Comment by crodas** [comment]
I'm working on t today @razvanphp. I had a busy schedule lately

**Comment by crodas** [comment]
@@michael-grunder @nicolasff @razvanphp  Fixed all merge issues. I did it against master though. Should I do the same against develop?

**Comment by crodas** [comment]
Any update on this?

**Comment by bgortney** [comment]
Any plans to merge msgpack?

**Comment by crodas** [comment]
@bgortney I'm keen to merge it. But I'm not part of the phpredis team.

**Comment by bgortney** [comment]
Understood.  I tried your commits against the develop branch and it looks like there are now a lot of conflicts.  When/if I have time, I'm going to see if I can get them merged into that branch, which might make acceptance easier.

**Comment by crodas** [comment]
@bgortney I can resolve the conflicts, will it help?

**Comment by bgortney** [comment]
I'm not a member of the phpredis team so I can't say definitively, but, it would likely help, in my opinion.  I know it would help me, if it were my project.

It's silly for phpredis to not have msgpack support, when it's far superior to igbinary (I've seen similar to the numbers posted by @ParkFramework).

If you resolve the conflicts, I'll be happy to test and comment here, as feedback for both you and the team.

**Comment by bgortney** [comment]
FYI, I just did a pull request with msgpack support against the php7 branch -- #801.

**Comment by yatsukhnenko** [comment]
We have some problems with msgpack, so I'm going to merge #1050 after they will be resolved. Is there anyone who need pure JSON serializer?

**Comment by yatsukhnenko** [comment]
I'm closing this since nobody interested in JSON serializer

**Pull request closed without merging**
