### PR TITLE
Fix memory leeks

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by dzuelke** [comment]
Is this fix potentially for #852 and #853, @yatsukhnenko? :)

**Comment by yatsukhnenko** [comment]
I don't think so, @dzuelke. This commit only fixes leeks in two uncommon situations: malformed `INFO` reply and protocol error.

**Comment by yatsukhnenko** [comment]
@michael-grunder, uncommon situations but may happens

**Comment by michael-grunder** [comment]
Looks good

**Pull request merged**
