### PR TITLE
Add Sentinel support - Need feedbacks

### PR DESCRIPTION
**Pull request by euskadi31**
Hi,

I use actually Redis sentinel on one of my projects, the phpredis does not support it. 

I added 2 classes RedisSentinel and RedisMasterDiscovery, and a Redis::role() method. 

All the code was tested (I used phptest).

see: https://travis-ci.org/euskadi31/phpredis

I did not write the documentation about this change, I wait your returns. 

``` php
$master = new RedisMasterDiscovery();

$master->addSentinel(new RedisSentinel('192.168.50.40', 26379));
$master->addSentinel(new RedisSentinel('192.168.50.41', 26379));

$info = $master->getMasterAddrByName('mymaster');

var_dump($info);
```

Output

```
array(2) {
  [0]=>
  string(9) "127.0.0.1"
  [1]=>
  string(4) "6379"
}
```

What do you think about it?

### CODE REVIEW

**Comment by michael-grunder** [comment]
Wow nice!  I'm currently prepping to get (replace really) phpredis 3.0.0 (cluster support) into develop for that release, but I think this is a useful addition that we should incorporate!

I'l play around with it over the weekend and see what I can find.

Cheers!
Mike

**Comment by euskadi31** [comment]
Ok Thx ;)

**Comment by euskadi31** [comment]
Hi Michael,

Have you had time to play with?

Axel

**Comment by michael-grunder** [comment]
Hey,

I haven't played around with it yet, as I'm finalizing the redis cluster functionality, but we'll get this merged right after 3.0.0 comes out.

Cluster changes a lot of structural stuff around how Redis works (e.g. argument/command processing has been extracted into redis_commands.c such that both Redis and RedisCluster use the same code), so it will likely require some massaging to get into that branch.

Ideally you can just move your code around a bit and resubmit a pull against what will become the new develop branch such that you will get credit for the contribution (rather than me doing it and stealing all the credit).  :)

Cheers!
Mike

**Comment by euskadi31** [comment]
Ok ;)

**Comment by tslater** [comment]
+1, any word on when this will make it in?

**Comment by luto** [comment]
@euskadi31 that's some impressive work! Do you have any plans to integrate this into the current `develop`, which seems to have the redis-cluster features merged already.

**Comment by leucos** [comment]
Too bad this PR is still in the queue :/
Any plans on resurrecting it ?

**Comment by ktwalrus** [comment]
Is Sentinel supported now in 3.0.0? I need Sentinel support for an upcoming project.

**Comment by michael-grunder** [comment]
@ktwalrus It's not merged, no.  It'll require resolving some merge conflicts to get it into develop.  Then of course it'll require substantial modification to make it work in php7.

**Comment by euskadi31** [comment]
Ok, I'll try to do that today or tomorrow 😉

**Comment by yatsukhnenko** [comment]
Closing this PR in favor to #851

**Pull request closed without merging**
