### PR TITLE
Add sentinel support and tests

### PR DESCRIPTION
**Pull request by euskadi31**
Hi,

I use actually Redis sentinel on one of my projects, the phpredis does not support it. 

I added 2 classes RedisSentinel and RedisMasterDiscovery, and a Redis::role() method. 

All the code was tested (I used phptest).

see: https://travis-ci.org/euskadi31/phpredis

I did not write the documentation about this change, I wait your returns. 

``` php
$master = new RedisMasterDiscovery();

$master->addSentinel(new RedisSentinel('192.168.50.40', 26379));
$master->addSentinel(new RedisSentinel('192.168.50.41', 26379));

$info = $master->getMasterAddrByName('mymaster');

var_dump($info);
```

Output

```
array(2) {
  [0]=>
  string(9) "127.0.0.1"
  [1]=>
  string(4) "6379"
}
```

What do you think about it?

### CODE REVIEW

**Comment by euskadi31** [comment]
I await your feedback and if it's OK I'll add documentation in the README ;)

**Comment by euskadi31** [comment]
Ping

**Comment by michael-grunder** [comment]
Hi.

I haven't forgotten about this, but there are so many things to do regarding phpredis :)

I really want to merge develop and php7 as maintaining two branches is unwieldy.

Then we can merge big new stuff in.

**Comment by asimonf** [comment]
Is this going to get merged at some point?

**Comment by jippi** [comment]
@michael-grunder any plans to get this into mainline? :)

**Comment by djschilling** [comment]
@michael-grunder Do you still want to merge this? It would be really good to have sentinel support build in.

**Comment by yatsukhnenko** [comment]
Author should resolve conflicts first (rebase onto `develop`)

**Comment by djschilling** [comment]
It would be great if @euskadi31 would do that. But the pull request is now open since 25 Jun 2016 i don't know if he is still into this.

**Comment by euskadi31** [comment]
Sorry, this is my 2nd PR and I confess that I do not want to give time on this one...

**Comment by Flyrell** [comment]
It would be nice to resurrect this. Is this planned to be merged anytime soon? I mean... the thing is 4 years old and still needed. I'd like to take a look at it, but my knowledge of C is not really great.

**Comment by telemmaite** [comment]
Quite needed for any real production HA setup, please resurrect it!

**Comment by adumskis** [comment]
Any news about adding Redis Sentinel and phpredis?

**Comment by yedamao** [comment]
hi,

Any plan add sentinel support to phpredis ?

**Comment by yatsukhnenko** [comment]
@yedamao, yes, there are a plans but currently there is no time to adopt changes from this PR. I my mind there should be only one RedisSentinel class with implementation of all necessary functionality.

**Comment by yedamao** [comment]
@yatsukhnenko Thanks

**Comment by jasminmistry** [comment]
Can we support it for session save_path?

**Comment by captain-igloo** [comment]
In the main README under "Session Locking" it says "Locking feature is currently only supported for Redis setup with single master instance (e.g. classic master/slave Sentinel environment)" . 

Is this a mistake in the README, i.e it incorrectly says that Sentinel is supported?

**Comment by tomswinkels** [comment]
Any update? @yatsukhnenko 

Laravel remove predis from default and added phpredis but we use sentinel.

**Comment by mikhailjan** [comment]
This would be a huge improvement for me. I'm currently not able to have a high availability Redis caching system in my PHP app.

**Comment by zetas** [comment]
Yea, this would be amazing. I can't have an HA Redis cluster without it right now :(

**Comment by K12Tech** [comment]
We are using specific provider's Redis as service and it allows connection only though sentinel so we are stuck with using both - predis for HA session storage and phpredis for data storage as performance is critical and phpredis is just so much better for it.

**Comment by yatsukhnenko** [comment]
Closing this PR in favour of #1689

**Pull request closed without merging**
