### PR TITLE
Work around PHP bug of liveness checking

### LINKED ISSUE #70: debug read error on connection
Hi there,

I am getting a lot of "read error on connection" errors. Server is under load, but not a lot. I traced this to always happen here:
- library.c
- redis_sock_read
- php_stream_gets -> this returns NULL, so it triggers the exception.

Any way I can further debug this to figure out why it happens?

Thanks,
Sorin

### PR DESCRIPTION
**Pull request by shafreeck**
### I think this patch may fix #70 .

There are two main reason to cause "read error on connecion". 
1. PHP has a [bug](https://github.com/php/php-src/pull/1456) of checking liveness of a connection. It may 
have a false positive judgement when a connection is indeed closed.
2. phpredis does not check if the redis command is sent successfully or not.

### You can reproduce it easily
1. Modify library.c and set errno to EWOULDBLOCK before any php_stream_eof. This will trigger the PHP bug.
2. Create test.php
```
<?php
$rds = new Redis();
try {
    $ret = $rds->pconnect("127.0.0.1", 6379);
    if ($ret == false) {
        echo "Connect return false";
        exit;
    }

    echo "Press any key to continue ...";
    fgetc(STDIN);
    var_dump($rds->get("hellophpredis"));
} catch (Exception $e) {
    var_dump ($e);
}
?>
```
3. Run `php test.php`
4. Login redis and `client kill` the test connection
5. Return back to test.php and press any key. Now you get the exception.

### CODE REVIEW

**Comment by michael-grunder** [comment]
This is going to make a lot of people very happy.  I'll test this locally and get it merged.

Nice find!

**Comment by shafreeck** [comment]
@michael-grunder 
I am glad to see the php bug [#70198](https://bugs.php.net/bug.php?id=70198) has been fixed though without merging my PR. I am wondering how is your test going ?

**Comment by shafreeck** [comment]
@michael-grunder Now my mate @git-hulk has proofed that it is exactly has this problem by throwing 'read error on connection' exception with errno which showed it is EAGAIN(11).

thanks to @git-hulk !

**Comment by shafreeck** [comment]
It takes too long too to merge this pr.  @michael-grunder I'd like to help if you have some problems.

**Comment by michael-grunder** [comment]
Many apologies for the long delay.  Tested and worked great.  Merged!

**Comment by parhamr** [comment]
Apologies for the skepticism, but I want actual proof that this fixes #70. It appears there are several contexts where issue #70 was reported, and notably many of the reports were related to PHP-FPM coordination of resources and sockets across multiple processes.

Was this change tested against any of the examples where threading and forking could reproduce the bug?

**Comment by michael-grunder** [comment]
Sorry I didn't intend to close #70 by merging this request.  It may very well fix the problem for certain cases however.  Reopened.

**Comment by parhamr** [comment]
@michael-grunder thanks!

**Pull request merged**
