### PR TITLE
Update rpm packer for phpredis

### PR DESCRIPTION
**Pull request by JGodin-C2C**
## What:
This PR update the RPM packaging process. It uses now docker and the latest version of phpredis (5.3.0).
## Why:
The RPM packaging was from 2014. It needed to be refreshed.

### CODE REVIEW

**Comment by remicollet** [comment]
Sorry, but I don't think it make sense to maintain a spec file here.

Indeed this one is really outdated.

Your proposal is really not enough (missing optional dependency, compression libraries and extensions)

Better maintained in the RPM distribution itself.
https://src.fedoraproject.org/rpms/php-pecl-redis5/tree/master

Especially as binary packages are also produced there and available for 
* Fedora in official repository
* RHEL / CentOS 7 (for SCL) by the SCLo SIG, see https://blog.remirepo.net/post/2017/02/23/Additional-PHP-packages-for-RHSCL
* RHEL / CentOS 8, sadly blocked by infrastructure issues,  but see https://rpms.remirepo.net/temp/epel-temp.repo

IMHO, simply remove this "rpm" directory.

**Comment by JGodin-C2C** [comment]
Hey Remi, thanks for taking the time to answer me. 

You are making a lot of good points here. I actually did not found the rspec that you had linked here before, thank you. 

I was trying to understand the problem RHEL8 actually have ( As it is my need ). I found your conversation about this elsewhere but could not understand the problem, i thus took the initiative to build my own packages and update this at it was , well, old. 

I think  deleting  this directory could be the right thing to do. I, however,  prefer the 'moved here' solution.

**Comment by remicollet** [comment]
> I was trying to understand the problem RHEL8 actually have 

Should read links in https://rpms.remirepo.net/temp/epel-temp.repo
Especially https://pagure.io/epel/issue/75 and linked other issues

**Review by remicollet — APPROVED** [review]
Simple README.md LGTM.

**Comment by JGodin-C2C** [comment]
Yup, i found it in the previous comment. Thanks for the head up. This does not sound good for the future of EPEL/PHP combo ...

**Comment by michael-grunder** [comment]
Merged, thanks!

**Pull request merged**
