### PR TITLE
Add msgpack serializer support to php7 branch

### PR DESCRIPTION
**Pull request by bgort**
This adds working msgpack serializer support to the php7 branch

This is particularly useful for those who previously relied on igbinary and were left without a decent serializer when moving to php 7.

I'm currently testing in dev with no issues; will report updates after further testing, and on moving to production.

### CODE REVIEW

**Comment by razvanphp** [comment]
Nice, but do you use a working msgpack-php version for php7? The branch seems to be gone from there, I'm wondering how can we test this.

**Comment by remicollet** [comment]
msgpack 2.0.1, compatible with PHP 7 is released

**Comment by bgortney** [comment]
Yes, msgpack 2.0.1 is available for php7 and works well. 

I've been using this in production with no issues for ~2 weeks now (~2 million commands sent).

**Comment by yatsukhnenko** [comment]
@bgort, could you squash your commits into one and rebase it onto `develop` brunch?

**Comment by bgort** [comment]
Yes.  May take me a bit (relatively busy), but I can do it.

**Comment by yatsukhnenko** [comment]
@bgort are you going to do rebasing in the near future?

**Comment by bgort** [comment]
I can try to do it today as long as not a lot has changed.  Thanks for the reminder.

**Comment by bgort** [comment]
Just opened a new PR - #1050 - with the rebase against develop in a single commit.  

Feel free to close this PR.

**Pull request closed without merging**
