### PR TITLE
Issue #1393

### PR DESCRIPTION
**Pull request by yatsukhnenko**
The interface is similar to the `RedisCluster::scan`

### CODE REVIEW

**Review by michael-grunder — APPROVED** [review]

**Comment by yatsukhnenko** [comment]
@akalongman could you test changes?

**Comment by michael-grunder** [comment]
Merged via 8689ab1c17a13034d9c8d0b7a011331cae9e5311

**Comment by akalongman** [comment]
@yatsukhnenko should I test `develop` branch?

**Comment by yatsukhnenko** [comment]
@akalongman yes, changes are already merged

**Comment by akalongman** [comment]
I've tested, seems like works everything. Thank you :heart_eyes:

**Comment by akalongman** [comment]
Waiting for `develop` branch release :pray:

**Pull request closed without merging**
