### PR TITLE
WIP: php7 compatibility

### PR DESCRIPTION
**Pull request by yatsukhnenko**
using zend_hash_str_find+zend_hash_str_find_ptr instead of zend_hash_find

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder, could you take a look? `sortAsc` test failed and I don't see what is wrong :(

**Comment by michael-grunder** [comment]
@yatsukhnenko I got an email notification that you were having issues with `sortAsc` but it seems to have gone missing here on github proper.  I don't see any failing tests for this branch but perhaps I'm missing something?

Also, if you don't mind you can just create your own working branches here rather than on your own copy of the repo because that way we could both commit to the same place, and I don't have to `git fetch` your version to test stuff.

Cheers!
Mike

**Comment by yatsukhnenko** [comment]
@michael-grunder, sorry for confusion. There were an error in my code but I fixed it and changed my previous message.
OK next time I'll create new brunch here :)

**Comment by yatsukhnenko** [comment]
btw, @michael-grunder, you can just checkout to PR's commit by hash insead of fetching from my repo :smiley_cat:

**Comment by yatsukhnenko** [comment]
@michael-grunder, did you review the code? I'm going to merge this tomorrow and start working on the next portion of changes :)

**Comment by michael-grunder** [comment]
I'll try to take a look at it today but feel free to merge!  I'm sure it's fine :)

**Pull request merged**
