### PR TITLE
Synchronize Redis and RedisSentinel constructors

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder what do you think about this change?

**Comment by michael-grunder** [comment]
@yatsukhnenko Sorry, I will go through this today.

**Review by michael-grunder — APPROVED** [review]
This looks good.

That said, we're going to probably need to find a way to soften the backward compatibility issues (for this and `Redis` itself).  We can deal with that later though :smile:

**Comment by yatsukhnenko** [comment]
> backward compatibility issues

We will deal with that later :smile:

**Comment by ostrolucky** [comment]
So indeed this breaks stuff for consumers quite severily https://github.com/snc/SncRedisBundle/actions/runs/4349246897/jobs/7598690557

**Comment by ostrolucky** [comment]
Is this how BC layer should be written? https://github.com/snc/SncRedisBundle/commit/7e436fbcbe6109513101077fe103a1de3c78bce5

**Pull request merged**
