### PR TITLE
fix #1074 bad type cast

### LINKED ISSUE #1074: Type confusion
In "redis_key_long_cmd"

```
    strlen_t key_len;
    key_free = redis_key_prefix(redis_sock, &key, (int *)&key_len);
```

You CANNOT do such cast (it may work on little endian, but will raise very bad things on big endian)

### PR DESCRIPTION
**Pull request by remicollet**
Still WIP, it seems there is some other bad cast (redis_serialize)

### CODE REVIEW

**Comment by remicollet** [comment]
Travis seems happy, and test pass on all 64bits arch, see https://koji.fedoraproject.org/koji/taskinfo?taskID=17011849

BTW still have soem bad [-Wincompatible-pointer-types] on 32bits  warnings see https://kojipkgs.fedoraproject.org//work/tasks/1856/17011856/build.log

**Comment by remicollet** [comment]
See: https://koji.fedoraproject.org/koji/taskinfo?taskID=17012116

* All builds ok.
* No warning in all arch
* Test suite pass on all 64 bits arch.

So ready for review

**Comment by remicollet** [comment]
Last commit is not directly related to this issue... but so minor ;)

**Comment by yatsukhnenko** [comment]
@remicollet, looks good but I see segfault on my gentoo box with php7.0 I'll try to find the reason...

**Comment by yatsukhnenko** [comment]
Nevermind :) It was my local gentoo-related problem

**Pull request merged**
