### PR TITLE
Sessions: Added check for network problems in locking loop

### PR DESCRIPTION
**Pull request by SkydiveMarius**
Solves #1412.

For simulating network problems, tcpkill was the best option in my eyes.
Unfortunately this requires executing the test with root privileges. 
Using [CLIENT KILL](https://redis.io/commands/client-kill) was not sufficient as its just causing a regular connection close.
Suggestions for better options are welcome.

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@SkydiveMarius thanks for this PR! I'm OK with changes in extension but I don't like the tests and especially dependency on tcpkill.

**Comment by SkydiveMarius** [comment]
> I'll create another PR with my vision of fix. @SkydiveMarius could you review it when it will be ready?

Of course, thank you!

**Comment by yatsukhnenko** [comment]
@SkydiveMarius You use the number of **sent** bytes as indicator of **received** response status. Your fix will not work when `redis_sock_gets` in `redis_sock_read` fails

**Comment by SkydiveMarius** [comment]
@yatsukhnenko Alright, closing in favor of #1488.

**Comment by yatsukhnenko** [comment]
@SkydiveMarius, thanks! Merged!

**Pull request closed without merging**
