### PR TITLE
Allow to specify server address as schema://host

### PR DESCRIPTION
**Pull request by yatsukhnenko**
This PR is related to issue #1314

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder if you OK with this change I'll update documentation

**Comment by michael-grunder** [comment]
The change seems to work just fine (although I only tested `tcp://`).  I'm fine with incorporating it but we probably want to clearly document that these aren't going to work:

```
redis://localhost
tcp://localhost:6379
```

Or we could support a host and port in the schema but that would require more parsing.

**Comment by yatsukhnenko** [comment]
I prefer to add a notice about this change in documentation. IMO ideally we should parse connection strings like `schema://password@host:port/db` or use array with parameters.
This implementation is just initial support which gives us feedback from users :)

**Comment by larowlan** [comment]
Was there a plan to add support for clusters over TLS too?

**Pull request merged**
