### PR TITLE
WIP: php7 compatibility

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Implementation of ZEND_HASH_FOREACH_VAL macro for php7 compatibility

### CODE REVIEW

**Comment by yatsukhnenko** [comment]
@michael-grunder, I'm going to apply the same patch on the php7 brunch after your review :)

**Comment by yatsukhnenko** [comment]
And now we can use smart_string instead of smart_str on both `develop` and `php7` brunches :)

**Comment by michael-grunder** [comment]
Hey,

Tests are working fine on this branch locally.  Hopefully I can help soon. :)

**Comment by yatsukhnenko** [comment]
If you don't mind I'll merge this PR and next time I'll open new one for new portion if changes

**Pull request merged**
