### PR TITLE
make phpredis support php7

### PR DESCRIPTION
**Pull request by zxcvdavid**
#508 is done.
There is no segfault when running ````TestRedis.php```` anymore.
But it still needs more test cases.
It is base on ````feature/redis_cluster```` branch.

### CODE REVIEW

**Comment by shouze** [comment]
:+1:

**Comment by shouze** [comment]
any hope to this this PR merged?

**Comment by coneo** [comment]
:+1:

**Comment by Ekhoo** [comment]
:+1:

**Comment by gmorel** [comment]
:+1:

**Comment by stephpy** [comment]
:+1:

**Comment by MikaFima** [comment]
:+1:

**Comment by shouze** [comment]
php 7 is beta 3 now... and this PR is opened since almost 1 year... any news?!

**Comment by michael-grunder** [comment]
I want to make phpredis support php7 for sure, but this request would break phpredis for all previous versions of php, so simply merging it isn't feasible.

Generally the way php libraries handle differing library versions is to wrap code in ```#ifdef``` statements, but in the case of php7 I think that would clutter the code far too much.  So the best solution (at least for the near or medium term) is to maintain two separate branches.

I'll try and make some time this weekend to see about the best way forward.

Cheers
Mike

**Comment by shouze** [comment]
ok thank you for details not that easy indeed!

**Comment by Sean-Der** [comment]
Hey @michael-grunder @zxcvdavid !

It looks like PR has fallen out of date (still has references to smart_str (instead of smart_string) when I went to compile it), do you still have time to work on this @zxcvdavid or would you mind me opening a PR against your php7 branch that fixes things that have changed?

**Comment by zxcvdavid** [comment]
Hey @Sean-Der ,
Plz go ahead. :)

**Comment by shouze** [comment]
ok guys... so php 7 stable will be released in a month or so...

**Comment by Spy-Seth** [comment]
:+1:

**Comment by skyred** [comment]
I tried to build phpredis against PHP 7.0 RC1, it failed, the error is below:

````
/usr/src/php/ext/redis/common.h:3:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include <ext/standard/php_smart_str.h>
````
The build detail can be found: https://hub.docker.com/r/insready/php-fpm-for-cms/builds/byaywfxzb4cn73mbdsddm3s/

Comparing to buiding against PHP 5.6, it works, the build detail is:
https://hub.docker.com/r/insready/php-fpm-for-cms/builds/b8skir5csfkudcjkpjhcntk/

**Comment by Sean-Der** [comment]
I have a branch that is compiling [here](https://github.com/Sean-Der/phpredis/tree/php7)

Going to start running tests now, also TODOs need to be resolved for memleaks.

**Comment by michael-grunder** [comment]
@Sean-Der Once I push and PECL release cluster support, I'll go ahead and merge these changes into a branch on this repo as well.  It's unfortunate having to keep it in a separate branch, I don't see how we can avoid it given that it breaks compatibility with older PHP versions.

**Comment by Sean-Der** [comment]
@michael-grunder Thank you so much for responding so quickly!

So good news, I saw how behind the branch was compared to master (tried to rebase) so I started over and have a much up to date branch on my fork [here](https://github.com/Sean-Der/phpredis/tree/php7-new) am I doing the right thing basing my work off master?

I *think* there will be better extension tooling available via [pickle](https://github.com/FriendsOfPHP/pickle) I know it stinks having to maintain two branches, but all the preprocessor stuff would get really funky I think. If we decided eventually that it actually is better I am up for the challenge :)

thanks!

**Comment by Sean-Der** [comment]
Hey everyone I open PR #654 which is against the current version of develop.

I am actively working on it and fixing test fails at the moment (it compiles but has run time issues)

If anyone wants to help me work on it, would really appreciate it. Especially with finding tests fails (especially finding the easy tests first, since a segfault will stop all the tests running and try to get the basics down)

thanks!

**Comment by shouze** [comment]
@Sean-Der yes, how can I help? Maybe can you create some issues?

**Comment by Sean-Der** [comment]
Hey @shouze thanks for wanting to get involved!

So right now we have two branches [mine](https://github.com/Sean-Der/phpredis/tree/php7-new)  and [edtechd](https://github.com/edtechd/phpredis) they both compile but I don't know the exact number of test fails on each.

After we figure out the right way to co-ordinate everyones work it would be really great if we could figure out a way to run all the tests, and not die if we have a segfault. (Maybe there is a way now, but if there isn't it might not be that hard to script etc...)

**Comment by shouze** [comment]
Roger that. So prior to open issues we miss a better overview, to have a complete map of failing tests?

**Comment by michael-grunder** [comment]
Do you guys have a recommendation for which php7 I should use to test through this stuff?  I was just going to get the one here, but let me know if that's wrong for some reason:
https://github.com/php/php-src/tree/PHP-7.0.0

**Comment by Sean-Der** [comment]
@michael-grunder That looks right to me! I just have a copy of master that I rebuild every couple of days to build/test against.

What do you think about consolidating PHP 7 PRs, we have three branches currently and I would really like to have a *blessed* one to work against.

thanks!

**Comment by Sean-Der** [comment]
Hey @shouze would you mind checking out the version [here](https://github.com/phpredis/phpredis/pull/654)? It passes the test suite, and I am gonna start using it now. It still has memory leaks and needs finishing touches, but it works!

Will continue working on it in the coming days.

thanks!

**Comment by robanlee123** [comment]
:+1:

**Comment by Jerry-Shaw** [comment]
That is great, @Sean-Der . I am going to try compile it in the afternoon, and make some tests.

Any bug will be reported if caught.

**Comment by Sean-Der** [comment]
Awesome, appreciate it @Jerry-Shaw I have just been running the existing test suite using 
`php -dextension=$PATH_TO_REDIS.-o tests/TestRedis.php` so I think I am missing out on the cluster tests. I will try to hit those tomorrow (heading to bed now)

thanks!

**Comment by gmorel** [comment]
:+1:

**Pull request closed without merging**
