### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by yatsukhnenko**

### CODE REVIEW

**Comment by michael-grunder** [comment]
Merged.  Now I need to read about how all of this automated "testing" stuff works :)

**Comment by yatsukhnenko** [comment]
Just sign in on travis-ci.org with phpredis account and activate repository :)

**Comment by michael-grunder** [comment]
OK It should be authorized.  Apparently it'll start doing it's thing when
we push to the repo.

On Thu, Aug 4, 2016 at 9:17 AM, Pavlo Yatsukhnenko <notifications@github.com

**Comment by michael-grunder** [comment]
Widget is up, passes on `develop`.  I'll see about getting it into php7 too.

**Comment by yatsukhnenko** [comment]
I have already done configuration for php 7 branch + added testing on different versions of php for develop brunch

**Comment by michael-grunder** [comment]
Awesome.  Feel free to merge it in!

**Pull request merged**
